### ISSUE TITLE
UI UX Issue: Meaning of the buttons is not evident or self explanatory at first glance

### ISSUE THREAD

**Issue by ManaliTanna** [gcivil-nyu-org/INET-Monday-Fall2023-Team-3#72]
This is a UI UX issue and **not** of utmost importance but the meaning of the buttons (as seen in screenshot) is not evident or self explanatory at first glance to someone who does not have context and it might help to have a text when you hover over the buttons. or to keep it simple, some text near (or on) the button itself.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9pQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4e8a95dc27e27eac9fc5aa5e38549ae608b074a/image.png)

**Comment by IreneLXR** [comment]
Thanks for the suggestion! have implemented hover message for those button.
